[versions]
composeCompiler = "1.4.4"

[plugins]
spotless = "com.diffplug.spotless:6.17.0"
ksp = "com.google.devtools.ksp:1.8.10-1.0.9"

[libraries]
gradlePlugin-android = "com.android.tools.build:gradle:7.4.2"
gradlePlugin-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.10"
gradlePlugin-mavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.25.1"
gradlePlugin-ksp = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.8.20-1.0.10"

#https://github.com/google/accompanist
accompanist-uicontroller = "com.google.accompanist:accompanist-systemuicontroller:0.30.0"
accompanist-drawablepainter = "com.google.accompanist:accompanist-drawablepainter:0.30.0"
accompanist-placeholder = "com.google.accompanist:accompanist-placeholder:0.30.0"

#https://developer.android.com/jetpack/androidx/releases/activity
activity-core = "androidx.activity:activity-ktx:1.7.0"
activity-compose = "androidx.activity:activity-compose:1.7.0"

#https://developer.android.com/jetpack/androidx/releases/annotation
annotation = "androidx.annotation:annotation:1.6.0"

#https://developer.android.com/jetpack/androidx/releases/appcompat
appcompat-core = "androidx.appcompat:appcompat:1.6.1"
appcompat-resources = "androidx.appcompat:appcompat-resources:1.6.1"

#https://developer.android.com/jetpack/androidx/releases/core
core = "androidx.core:core-ktx:1.9.0"
core-splash = "androidx.core:core-splashscreen:1.0.0"

#https://developer.android.com/jetpack/androidx/releases/lifecycle
lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1"
lifecycle-viewmodel-savedstate = "androidx.lifecycle:lifecycle-viewmodel-savedstate:2.6.1"
lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.1"
lifecycle-process = "androidx.lifecycle:lifecycle-process:2.6.1"
lifecycle-service = "androidx.lifecycle:lifecycle-service:2.6.1"

test-core = "androidx.test:core-ktx:1.5.0"

test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
test-junit = "androidx.test.ext:junit-ktx:1.1.5"
test-rules = "androidx.test:rules:1.5.0"
test-runner = "androidx.test:runner:1.5.2"
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

#https://developer.android.com/jetpack/androidx/releases/compose
compose-foundation = "androidx.compose.foundation:foundation:1.4.0"
compose-material = "androidx.compose.material:material:1.4.0"
compose-tooling = "androidx.compose.ui:ui-tooling:1.4.0"
compose-ui-test = "androidx.compose.ui:ui-test-junit4:1.3.3"

#https://github.com/Kotlin/kotlinx.coroutines
coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"

junit = "junit:junit:4.13.2"

#https://github.com/JetBrains/kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

ktlint = "com.pinterest.ktlint:ktlint-core:0.48.2"

material = "com.google.android.material:material:1.8.0"

#https://github.com/square/okhttp
okhttp-core = "com.squareup.okhttp3:okhttp:4.10.0"
okhttp-logging = "com.squareup.okhttp3:logging-interceptor:4.10.0"
okhttp-mockwebserver = "com.squareup.okhttp3:mockwebserver:4.10.0"

svg = "com.caverock:androidsvg-aar:1.4"

#https://github.com/orbit-mvi/orbit-mvi
mvi-core = "org.orbit-mvi:orbit-core:4.6.1"
mvi-vm = "org.orbit-mvi:orbit-viewmodel:4.6.1"
mvi-compose = "org.orbit-mvi:orbit-compose:4.6.1"
mvi-test = "org.orbit-mvi:orbit-test:4.6.1"

#https://github.com/qoqa/glide-svg
koin-core = "io.insert-koin:koin-core:3.4.0"
koin-android = "io.insert-koin:koin-android:3.4.0"
koin-compose = "io.insert-koin:koin-androidx-compose:3.4.3"

#https://github.com/qiushui95/AndroidInitializer
initializer = "com.github.qiushui95:AndroidInitializer:1.0.11"

#https://github.com/JodaOrg/joda-time
jodatime = "joda-time:joda-time:2.12.5"

#https://square.github.io/leakcanary/getting_started/
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.10"

#https://github.com/Tencent/MMKV/blob/master/README_CN.md
mmkv = "com.tencent:mmkv-static:1.2.15"

#https://github.com/iqiyi/xCrash/blob/master/README.zh-CN.md
xcrash = "com.iqiyi.xcrash:xcrash-android-lib:3.1.0"

#https://github.com/li-xiaojun/XPopup
xpopup = "com.github.li-xiaojun:XPopup:2.9.19"

#https://github.com/getActivity/XXPermissions
permission = "com.github.getActivity:XXPermissions:16.8"

#https://github.com/srikanth-lingala/zip4j
zip4j = "net.lingala.zip4j:zip4j:2.11.5"

#https://bugly.qq.com/docs/user-guide/instruction-manual-android/?v=1.0.0
bugly = "com.tencent.bugly:crashreport:4.1.9"

#https://github.com/bumptech/glide
glide-core = "com.github.bumptech.glide:glide:4.15.1"
glide-compose = "com.github.bumptech.glide:compose:1.0.0-alpha.3"
glide-ksp = "com.github.bumptech.glide:ksp:4.15.1"
glide-okhttp = "com.github.bumptech.glide:okhttp3-integration:4.15.1"
#https://github.com/qoqa/glide-svg
glide-svg = "com.github.qoqa:glide-svg:4.0.2"

#https://github.com/square/moshi
moshi-core = "com.squareup.moshi:moshi:1.14.0"
moshi-ksp = "com.squareup.moshi:moshi-kotlin-codegen:1.14.0"

#https://github.com/square/retrofit
retrofit-core = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-moshi = "com.squareup.retrofit2:converter-moshi:2.9.0"
retrofit-scalars = "com.squareup.retrofit2:converter-scalars:2.9.0"

#https://developer.android.com/jetpack/androidx/releases/room
room-core = "androidx.room:room-ktx:2.5.1"
room-ksp = "androidx.room:room-compiler:2.5.1"

#https://github.com/facebook/stetho
stetho = "com.facebook.stetho:stetho:1.6.0"
stetho-okhttp = "com.facebook.stetho:stetho-okhttp3:1.6.0"

#https://github.com/wasabeef/transformers
transformers-glide = "jp.wasabeef.transformers:glide:1.0.6"
transformers-gpu = "jp.wasabeef.transformers:glide-gpu:1.0.6"

#https://github.com/skydoves/landscapist
landscapist-glide = "com.github.skydoves:landscapist-glide:2.1.9"
landscapist-placeholder = "com.github.skydoves:landscapist-placeholder:2.1.9"
landscapist-animation = "com.github.skydoves:landscapist-animation:2.1.9"
landscapist-transformation = "com.github.skydoves:landscapist-transformation:2.1.9"
landscapist-palette = "com.github.skydoves:landscapist-palette:2.1.9"

#https://github.com/raamcosta/compose-destinations
compose-destinations-core = "io.github.raamcosta.compose-destinations:core:1.8.38-beta"
compose-destinations-ksp = "io.github.raamcosta.compose-destinations:ksp:1.8.38-beta"

#https://github.com/airbnb/lottie-android
lottie-view="com.airbnb.android:lottie:6.0.0"
lottie-compose="com.airbnb.android:lottie-compose:6.0.0"