[versions]
#https://developer.android.com/jetpack/androidx/releases/compose-compiler
composeCompiler = "1.4.6"
#https://github.com/google/ksp
ksp = "1.8.20-1.0.11"
#https://github.com/JetBrains/kotlin
kotlin = "1.8.20"
#https://github.com/google/accompanist
accompanist = "0.30.1"
#https://developer.android.com/jetpack/androidx/releases/activity
activity = "1.7.1"
#https://developer.android.com/jetpack/androidx/releases/appcompat
appcompat = "1.6.1"
#https://developer.android.com/jetpack/androidx/releases/lifecycle
lifecycle = "2.6.1"
#https://developer.android.com/jetpack/androidx/releases/compose
compose = "1.4.2"
#https://github.com/Kotlin/kotlinx.coroutines
coroutines = "1.6.4"
#https://github.com/square/okhttp
okhttp = "4.10.0"
#https://github.com/orbit-mvi/orbit-mvi
mvi = "4.6.1"
#https://github.com/InsertKoinIO/koin
koinCore = "3.4.0"
koinAndroid = "3.4.0"
koinCompose = "3.4.4"
#https://github.com/bumptech/glide
glide = "4.15.1"
#https://github.com/wasabeef/transformers
transformers = "1.0.6"
#https://github.com/square/moshi
moshi = "1.14.0"
#https://github.com/square/retrofit
retrofit = "2.9.0"
#https://developer.android.com/jetpack/androidx/releases/room
room = "2.5.1"
#https://github.com/facebook/stetho
stetho = "1.6.0"
#https://github.com/skydoves/landscapist
landscapist = "2.1.11"
#https://github.com/airbnb/lottie-android
lottie = "6.0.0"
#https://github.com/LuckSiege/PictureSelector
selector = "v3.11.1"
#https://developer.android.com/jetpack/androidx/releases/fragment
fragment = "1.5.7"

[plugins]
#https://github.com/diffplug/spotless
spotless = "com.diffplug.spotless:6.18.0"
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
validator = "org.jetbrains.kotlinx.binary-compatibility-validator:0.13.1"

[libraries]
gradlePlugin-android = "com.android.tools.build:gradle:7.4.2"
gradlePlugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
#https://github.com/vanniktech/gradle-maven-publish-plugin
gradlePlugin-mavenPublish = "com.vanniktech:gradle-maven-publish-plugin:0.25.2"
gradlePlugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

#https://github.com/Blankj/AndroidUtilCode/blob/master/lib/utilcode/README-CN.md
android-utils = "com.blankj:utilcodex:1.31.1"

#https://github.com/google/accompanist
accompanist-uicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompanist-drawablepainter = { group = "com.google.accompanist", name = "accompanist-drawablepainter", version.ref = "accompanist" }
accompanist-placeholder = { group = "com.google.accompanist", name = "accompanist-placeholder", version.ref = "accompanist" }

#https://developer.android.com/jetpack/androidx/releases/activity
activity-core = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }

#https://developer.android.com/jetpack/androidx/releases/annotation
annotation = "androidx.annotation:annotation:1.6.0"

#https://developer.android.com/jetpack/androidx/releases/appcompat
appcompat-core = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
appcompat-resources = { group = "androidx.appcompat", name = "appcompat-resources", version.ref = "appcompat" }

#https://developer.android.com/jetpack/androidx/releases/core
core = "androidx.core:core-ktx:1.9.0"
core-splash = "androidx.core:core-splashscreen:1.0.0"

#https://developer.android.com/jetpack/androidx/releases/lifecycle
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-savedstate = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }

test-junit = "junit:junit:4.13.2"
test-core = "androidx.test:core-ktx:1.5.0"
test-espresso = "androidx.test.espresso:espresso-core:3.5.1"
test-junit-ext = "androidx.test.ext:junit-ktx:1.1.5"
test-rules = "androidx.test:rules:1.5.0"
test-runner = "androidx.test:runner:1.5.2"
test-uiautomator = "androidx.test.uiautomator:uiautomator:2.2.0"

#https://developer.android.com/jetpack/androidx/releases/compose
compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose" }

#https://github.com/Kotlin/kotlinx.coroutines
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

#https://github.com/JetBrains/kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit" }

#https://github.com/pinterest/ktlint
ktlint = "com.pinterest.ktlint:ktlint-core:0.48.2"

#https://github.com/material-components/material-components-android
material = "com.google.android.material:material:1.8.0"

#https://github.com/square/okhttp
okhttp-core = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp" }

#https://github.com/orbit-mvi/orbit-mvi
mvi-core = { group = "org.orbit-mvi", name = "orbit-core", version.ref = "mvi" }
mvi-vm = { group = "org.orbit-mvi", name = "orbit-viewmodel", version.ref = "mvi" }
mvi-compose = { group = "org.orbit-mvi", name = "orbit-compose", version.ref = "mvi" }
mvi-test = { group = "org.orbit-mvi", name = "orbit-test", version.ref = "mvi" }

#https://github.com/InsertKoinIO/koin
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koinCore" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koinAndroid" }
koin-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koinCompose" }

#https://github.com/qiushui95/AndroidInitializer
initializer = "com.github.qiushui95:AndroidInitializer:1.0.16"

#https://github.com/JodaOrg/joda-time
jodatime = "joda-time:joda-time:2.12.5"

#https://square.github.io/leakcanary/getting_started/
leakcanary = "com.squareup.leakcanary:leakcanary-android:2.10"

#https://github.com/Tencent/MMKV/blob/master/README_CN.md
mmkv = "com.tencent:mmkv-static:1.2.15"

#https://github.com/iqiyi/xCrash/blob/master/README.zh-CN.md
xcrash = "com.iqiyi.xcrash:xcrash-android-lib:3.1.0"

#https://github.com/li-xiaojun/XPopup
xpopup = "com.github.li-xiaojun:XPopup:2.9.19"

#https://github.com/getActivity/XXPermissions
permission = "com.github.getActivity:XXPermissions:18.0"

#https://github.com/srikanth-lingala/zip4j
zip4j = "net.lingala.zip4j:zip4j:2.11.5"

#https://bugly.qq.com/docs/user-guide/instruction-manual-android/?v=1.0.0
bugly = "com.tencent.bugly:crashreport:4.1.9.2"

#https://github.com/bumptech/glide
glide-core = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-okhttp = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }

#https://github.com/wasabeef/transformers
transformers-glide = { group = "jp.wasabeef.transformers", name = "glide", version.ref = "transformers" }
transformers-gpu = { group = "jp.wasabeef.transformers", name = "glide-gpu", version.ref = "transformers" }

#https://github.com/square/moshi
moshi-core = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-ksp = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }

#https://github.com/square/retrofit
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit-scalars = { group = "com.squareup.retrofit2", name = "converter-scalars", version.ref = "retrofit" }

#https://developer.android.com/jetpack/androidx/releases/room
room-core = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-ksp = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

#https://github.com/facebook/stetho
stetho-core = { group = "com.facebook.stetho", name = "stetho", version.ref = "stetho" }
stetho-okhttp = { group = "com.facebook.stetho", name = "stetho-okhttp3", version.ref = "stetho" }

#https://github.com/skydoves/landscapist
landscapist-glide = { group = "com.github.skydoves", name = "landscapist-glide", version.ref = "landscapist" }
landscapist-placeholder = { group = "com.github.skydoves", name = "landscapist-placeholder", version.ref = "landscapist" }
landscapist-animation = { group = "com.github.skydoves", name = "landscapist-animation", version.ref = "landscapist" }
landscapist-transformation = { group = "com.github.skydoves", name = "landscapist-transformation", version.ref = "landscapist" }
landscapist-palette = { group = "com.github.skydoves", name = "landscapist-palette", version.ref = "landscapist" }

#https://github.com/airbnb/lottie-android
lottie-view = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }

#https://github.com/ChuckerTeam/chucker
chucker = "com.github.chuckerteam.chucker:library:3.5.2"

#https://developer.android.com/jetpack/androidx/releases/constraintlayout
compose-constraint = "androidx.constraintlayout:constraintlayout-compose:1.0.1"

#https://github.com/LuckSiege/PictureSelector
selector-core = { group = "io.github.lucksiege", name = "pictureselector", version.ref = "selector" }
selector-compress = { group = "io.github.lucksiege", name = "compress", version.ref = "selector" }
selector-crop = { group = "io.github.lucksiege", name = "ucrop", version.ref = "selector" }
selector-camerax = { group = "io.github.lucksiege", name = "camerax", version.ref = "selector" }

#https://help.aliyun.com/document_detail/32043.html?spm=a2c4g.32041.0.0.5c6b3c6bC8T5kQ
alioss = { group = "com.aliyun.dpa", name = "oss-android-sdk", version = "2.9.13" }

#https://developer.android.com/jetpack/androidx/releases/fragment
fragment-core = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
fragment-test = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment" }
