name: Update Dependencies

on:
  workflow_dispatch:
    schedule:
      - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        env:
          GITHUB_CONTEXT: ${{secrets.TEST2}}
        run: |
          echo "${{secrets.HERO_NEXUS.TEST2}}"
      - uses: actions/checkout@v3
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Update dependencies
        run: |
          chmod 777 scripts/updateDeps.sh
          ./scripts/updateDeps.sh
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
#          token: ${{ secrets.PAT }}
          commit-message: 🤖 Update Dependencies
          committer: update-github-bot
          author: update-github-bot
          signoff: false
          branch: bot-update-deps
          delete-branch: true
          title: '🤖 Update Dependencies'
          body: Updated depedencies
          reviewers: ${{ github.actor }}
